title: NeurIPS Meetup Japan 2021
description:

event_time: December 6–⁠14, 2021
event_venue: Online
event_description: An online meetup for students, researchers, and engineers in machine learning, artificial intelligence, and related disciplines to share ideas and learn from each other.
register_link: https://www.google.com

contact: "neuripsmeetupjapan@gmail.com"
copyright: NeurIPS Meetup Japan

timezone: Asia/Tokyo

collections:
  - events
